apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80          # Exposing the service on port 80
      targetPort: 80     # The port inside the container
  type: LoadBalancer     # Use LoadBalancer to get an external IP address

